services:
  app:
    image: mysociety/ministers-gifts:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/ministers_gifts      
    volumes:
      - ./:/workspaces/ministers_gifts/